services:

  payment-service:
    build: ./payment-service
    container_name: payment-container
    ports:
      - "8082:8082"

  order-service:
    build: ./order-service
    container_name: order-container
    ports:
      - "8081:8081"
    depends_on:
      - payment-service

  customer-service:
    build: ./customer-service
    container_name: customer-container
    ports:
      - "8083:8083"